# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-10-23 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_auto_20181023_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermessage',
            name='object_id',
            field=models.CharField(auto_created=True, max_length=50, primary_key=True, serialize=False),
        ),
    ]
